include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - lib/data/models/*.g.dart
    - lib/firebase_options.dart
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
