name: share_lyrics
description: Flutter app to store song lyrics
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.3
  build_runner: ^2.4.11
  cached_network_image: ^3.3.1
  chopper: ^8.0.1+1
  chopper_generator: ^8.0.1
  cloud_firestore: ^5.0.2
  equatable: ^2.0.5
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mesh_gradient: ^1.3.7
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.1
  stream_transform: ^2.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sign_in_icons/
    - assets/song_media_icons/

spider:
  generate_tests: true
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: resources
  groups:
    - path: assets/sign_in_icons
      class_name: SignInIcons
      types: [ .svg ]
    - path: assets/song_media_icons
      class_name: SongMediaIcons
      types: [ .svg ]
